# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_COMMAND = ARGV[0]

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provision "shell", path: "provision.sh"

  if VAGRANT_COMMAND == "ssh"
    config.ssh.username = "speaker"
    config.ssh.password = 'speaker'
  end

  config.vm.synced_folder ".", "/mnt/vagrant"
end
