# -*- mode: ruby -*-
# vi: set ft=ruby :

# In order to lessen friction for students getting started, this course
# includes a custom Vagrant "box."
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provision "shell", path: "provision.sh"

  config.vm.synced_folder ".", "/mnt/vagrant"
end
